In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [2]:
## load the dataset
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
print(data.columns.tolist())

['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited']

In [4]:
## Preprocess the data
## Drop irrelevant columns
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, errors='ignore')

In [5]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
## Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [7]:
## Onehot encode 'Geography'
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder()
geo_encoder = onehot_encoder.fit_transform(data[['Geography']])
geo_encoder=onehot_encoder.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [8]:
onehot_encoder.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [9]:
geo_encoded_df = pd.DataFrame(geo_encoder.toarray(), columns=onehot_encoder.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [10]:
## Combine one hot encoded columns with the original dataframe
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [11]:
## Save the encoders and scaler
with open('label_encoder_gender.pkl', 'wb') as f:
    pickle.dump(label_encoder_gender, f)
with open('onehot_encoder_geography.pkl', 'wb') as f:
    pickle.dump(onehot_encoder, f)

In [12]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [13]:
## Divide the data into independent and dependent features
X = data.drop('Exited', axis=1)
y = data['Exited']

## Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


## Scale these features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [14]:
X_train_scaled

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [15]:
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

In [16]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

ANN IMPLEMENTATION

In [17]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

WARNING:tensorflow:From c:\Users\Swati Saxena\OneDrive\Desktop\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [18]:
## Build our ANN model
model = Sequential(
    [
        Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)), ## HL1 Connected to input layer
        Dense(32, activation='relu'), ## HL2
        Dense(1, activation='sigmoid') ## Output layer
    ]
)

WARNING:tensorflow:From c:\Users\Swati Saxena\OneDrive\Desktop\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [20]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.001)
loss=tensorflow.keras.losses.BinaryCrossentropy()

In [21]:
## compile the model
model.compile(optimizer=opt, loss=loss, metrics=['accuracy'])

In [22]:
## Set up the tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

long_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=long_dir, histogram_freq=1)

In [23]:
## Set up Early stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [24]:
## Train the model
history = model.fit(X_train_scaled, y_train, validation_data=(X_test_scaled, y_test), epochs=100, batch_size=32, callbacks=[early_stopping_callback,tensorflow_callback])

Epoch 1/100
WARNING:tensorflow:From c:\Users\Swati Saxena\OneDrive\Desktop\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\Swati Saxena\OneDrive\Desktop\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 1s 3ms/step - loss: 0.4445 - accuracy: 0.8109 - val_loss: 0.3814 - val_accuracy: 0.8340
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3736 - accuracy: 0.8475 - val_loss: 0.3553 - val_accuracy: 0.8515
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3500 - accuracy: 0.8556 - val_loss: 0.3466 - val_accuracy: 0.8585
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3425 - accuracy: 0.8580 - val_loss: 0.3452 - val_accuracy: 0.8620
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3376 - accuracy: 0.8624 - val_loss: 0.3429 - val_accuracy: 0.8585
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3340 - accuracy: 0.8615 - val_loss: 0.3411 - val_accuracy: 0.8615
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3309 - accuracy: 0.8634 - val_loss: 0.3437 - val_accuracy: 0.8565
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3290 - accuracy: 0.8637 - val_loss: 0.3386 - val_accuracy: 0.8640
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3259 - accuracy: 0.8660 - val_loss: 0.3383 - val_accuracy: 0.8640
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3232 - accuracy: 0.8664 - val_loss: 0.3406 - val_accuracy: 0.8575
Epoch 11/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3219 - accuracy: 0.8629 - val_loss: 0.3401 - val_accuracy: 0.8570
Epoch 12/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3182 - accuracy: 0.8668 - val_loss: 0.3386 - val_accuracy: 0.8605
Epoch 13/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3181 - accuracy: 0.8669 - val_loss: 0.3362 - val_accuracy: 0.8595
Epoch 14/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3154 - accuracy: 0.8670 - val_loss: 0.3371 - val_accuracy: 0.8615
Epoch 15/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3143 - accuracy: 0.8686 - val_loss: 0.3396 - val_accuracy: 0.8635
Epoch 16/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3116 - accuracy: 0.8696 - val_loss: 0.3538 - val_accuracy: 0.8570
Epoch 17/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3115 - accuracy: 0.8698 - val_loss: 0.3461 - val_accuracy: 0.8615
Epoch 18/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3107 - accuracy: 0.8692 - val_loss: 0.3421 - val_accuracy: 0.8610

In [25]:
model.save('model.h5')

c:\Users\Swati Saxena\OneDrive\Desktop\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [26]:
## load tensorboard extension
%load_ext tensorboard
%tensorboard --logdir logs/fit

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\Swati Saxena\OneDrive\Desktop\venv\Scripts\tensorboard.exe\__main__.py", line 2, in <module>
  File "C:\Users\Swati Saxena\OneDrive\Desktop\venv\Lib\site-packages\tensorboard\main.py", line 27, in <module>
    from tensorboard import default
  File "C:\Users\Swati Saxena\OneDrive\Desktop\venv\Lib\site-packages\tensorboard\default.py", line 30, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

In [27]:
%reload_ext tensorboard

In [32]:
%tensorboard --logdir logs/fit

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\Swati Saxena\OneDrive\Desktop\venv\Scripts\tensorboard.exe\__main__.py", line 2, in <module>
  File "c:\Users\Swati Saxena\OneDrive\Desktop\venv\Lib\site-packages\tensorboard\main.py", line 27, in <module>
    from tensorboard import default
  File "c:\Users\Swati Saxena\OneDrive\Desktop\venv\Lib\site-packages\tensorboard\default.py", line 30, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

In [29]:
pip install setuptools --upgrade

Requirement already satisfied: setuptools in c:\Users\Swati Saxena\OneDrive\Desktop\venv\Lib\site-packages (82.0.1)
Note: you may need to restart the kernel to use updated packages.

In [30]:
import subprocess
subprocess.run(["pip", "install", "--force-reinstall", "setuptools"], check=True)

CompletedProcess(args=['pip', 'install', '--force-reinstall', 'setuptools'], returncode=0)

In [31]:
import subprocess
subprocess.run([
    "pip", "uninstall", "tensorboard", "tensorboard-data-server", 
    "tensorboard-plugin-wit", "-y"
], check=True)

subprocess.run([
    "pip", "install", "tensorboard==2.13.0"
], check=True)

CompletedProcess(args=['pip', 'install', 'tensorboard==2.13.0'], returncode=0)

In [33]:
%tensorboard --logdir logs/fit

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\Swati Saxena\OneDrive\Desktop\venv\Scripts\tensorboard.exe\__main__.py", line 2, in <module>
  File "c:\Users\Swati Saxena\OneDrive\Desktop\venv\Lib\site-packages\tensorboard\main.py", line 27, in <module>
    from tensorboard import default
  File "c:\Users\Swati Saxena\OneDrive\Desktop\venv\Lib\site-packages\tensorboard\default.py", line 30, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

In [35]:
import subprocess
subprocess.Popen(["tensorboard", "--logdir", "logs/fit", "--port", "6006"])

print("Go to: http://localhost:6006")

Go to: http://localhost:6006

In [ ]:
## load the pickel files